#根据状态查找文章
SELECT
	P.ID AS ID,
	P.TITLE AS TITLE,
	M.VALUE AS COVER,
	P.CONTENT AS CONTENT,
	P.COMMENT_COUNT AS COMMENTCOUNT,
	P.CREATE_AT AS CREATEAT,
	P.REFERENCE AS REFERENCE,
	P.STATUS AS STATUS,
	P.USER_ID AS USERID,
	U.NAME AS USERNAME

FROM
	POST AS P,
	META AS M,
	USER AS U
WHERE
	P.STATUS=?
	AND
	P.USER_ID=U.ID
	AND
	P.COVER=M.KEY
ORDER BY P.CREATE_AT DESC
LIMIT ?,?