#查找首页文章列表
SELECT
	P.ID AS ID,
	U.AVATAR AS HEAD,
	P.TITLE AS TITLE,
	T.NAME AS TAG,
	U.NAME AS USERNAME,
	P.CREATE_AT AS TIME
FROM 
  POST AS P
  LEFT JOIN USER AS U ON P.USER_ID=U.ID
  LEFT JOIN POST_TAG AS PT ON P.ID=PT.POST_ID
  LEFT JOIN TAG AS T ON T.ID=PT.TAG_ID
WHERE
  P.STATUS=?
ORDER BY P.CREATE_AT DESC
LIMIT ?,?