#根据ID查询文章内容
SELECT
	P.ID AS ID,
	P.TITLE AS TITLE,
	P.CONTENT AS CONTENT,
	P.CREATE_AT AS CREATEAT,
	P.UPDATE_AT AS UPDATEAT,
	P.VIEW_COUNT AS VIEWCOUNT,
	P.COMMENT_COUNT AS COMMENTCOUNT,
	T.NAME AS TAG,
	U.AVATAR AS AVATAR,
	U.NAME AS USERNAME,
	U.ID AS USERID
FROM
	POST AS P
	LEFT JOIN USER AS U ON P.USER_ID = U.ID
	LEFT JOIN POST_TAG AS PT ON P.ID = PT.POST_ID
	LEFT JOIN TAG AS T ON PT.TAG_ID = T.ID
WHERE
	P.ID = ?